name: Bogyi Konyha - Konyhai Nyilvántartó
version: "0.1.12"
slug: bogyikonya
description: Konyhai és kamra nyilvántartó alkalmazás helyi adatokkal
url: "https://github.com/marsimiklos/bogyikitchen"
arch:
  - amd64
  - aarch64
  - armhf
startup: application
init: false
ports:
  8099/tcp: null
webui: http://[HOST]:[PORT:8099]

# --- AZ ALÁBBI SOROK A JAVÍTÁS ---
ingress: true
panel_icon: mdi:food-turkey
panel_title: Bogyi Konyha
# ---------------------------------

options: {}
schema: {}
