name: Bogyi Konyha - Konyhai Nyilv치ntart칩
version: "0.1.38"
slug: bogyikonya
description: Konyhai 칠s kamra nyilv치ntart칩 alkalmaz치s helyi adatokkal
url: "https://github.com/marsimiklos/bogyikitchen"
arch:
  - amd64
  - aarch64
  - armhf
startup: application
init: false

# Ezt hagyd benne, hogy ne legyen k칲ls콈 portnyit치s (Ingress alatt nem kell)
ports: {}

# 游댢 FONTOS R칄SZ
ingress: true
ingress_port: 8099
panel_icon: mdi:food-turkey
panel_title: Bogyi Konyha
host_network: false
options: {}
schema: {}
